<?php

declare(strict_types=1);

/*
 * BRIAPICollectionCopyLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BRIAPICollectionCopyLib;

/**
 * Baseurl aliases
 */
class Server
{
    public const SERVER_1 = 'Server 1';

    public const SERVER_2 = 'Server 2';

    public const AUTH_SERVER = 'auth server';
}
